### ISSUE TITLE
Should change the survey questions?

### ISSUE THREAD

**Issue by chaol12** [zikrya/Personal-Expense-Tracker#53]
I think the survey asks too much information from the users. If we were the user, would we like to provide too much personal information to an app when we just wants to keep track of our spending?  We may want to delete the questions that are asking about "major",  "source Of Income", " money Saved", "budget Categories", "total Expenses" and { one of these "notification Preferences" or "notification Method"}.  We may keep the "first Name", "last Name", "college", "graduation Date", "housing Situation", "monthly Income", "savings Goal",  "maximum Budget" or anything you think you would like to provide.

**Comment by aappacode** [comment]
Updated for asked changes in this PR: https://github.com/zikrya/Personal-Expense-Tracker/pull/56
