### ISSUE TITLE
PPT-006 -- Create Navbar and Route Pages

### ISSUE THREAD

**Issue by aappacode** [zikrya/Personal-Expense-Tracker#7]
Create a streamlined navigation bar
Connect/route all pages with conditional authentication

**Comment by aappacode** [comment]
@gaoqiangzhou add logout button to navbar?

**Comment by gaoqiangzhou** [comment]
> @gaoqiangzhou add logout button to navbar?
I forget that, but i just added the logout button

**Comment by aappacode** [comment]
completed last iteration
